//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ApplicationsDatapoint: APIModel {

    /** Count associated with timestamp */
    public var count: Double?

    /** Timestamp for the related count. */
    public var time: DateTime?

    public init(count: Double? = nil, time: DateTime? = nil) {
        self.count = count
        self.time = time
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        count = try container.decodeIfPresent("count")
        time = try container.decodeIfPresent("time")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(count, forKey: "count")
        try container.encodeIfPresent(time, forKey: "time")
    }

    public static func == (lhs: ApplicationsDatapoint, rhs: ApplicationsDatapoint) -> Bool {
        guard lhs.count == rhs.count else { return false }
        guard lhs.time == rhs.time else { return false }
        return true
    }
}
