//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ApplicationsSeries: APIModel {

    /** Collection of samples with time and value. */
    public var datapoints: [ApplicationsDatapoint]?

    /** Target to which to datapoints apply. */
    public var target: String?

    public init(datapoints: [ApplicationsDatapoint]? = nil, target: String? = nil) {
        self.datapoints = datapoints
        self.target = target
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        datapoints = try container.decodeArrayIfPresent("datapoints")
        target = try container.decodeIfPresent("target")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(datapoints, forKey: "datapoints")
        try container.encodeIfPresent(target, forKey: "target")
    }

    public static func == (lhs: ApplicationsSeries, rhs: ApplicationsSeries) -> Bool {
        guard lhs.datapoints == rhs.datapoints else { return false }
        guard lhs.target == rhs.target else { return false }
        return true
    }
}
