//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** When a Vendor Interaction provides rewards, they'll either let you choose one or let you have all of them. This determines which it will be. */
/** When a Vendor Interaction provides rewards, they'll either let you choose one or let you have all of them. This determines which it will be. */
public enum DestinyDestinyVendorInteractionRewardSelection: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
