//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** These Art Elements are meant to represent one-off visual effects overlaid on the map. Currently, we do not have a pipeline to import the assets for these overlays, so this info exists as a placeholder for when such a pipeline exists (if it ever will) */
public struct DestinyDefinitionsDirectorDestinyActivityGraphArtElementDefinition: APIModel {

    /** The position on the map of the art element. */
    public var position: [String: Any]?

    public init(position: [String: Any]? = nil) {
        self.position = position
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        position = try container.decodeAnyIfPresent("position")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeAnyIfPresent(position, forKey: "position")
    }

    public static func == (lhs: DestinyDefinitionsDirectorDestinyActivityGraphArtElementDefinition, rhs: DestinyDefinitionsDirectorDestinyActivityGraphArtElementDefinition) -> Bool {
        guard NSDictionary(dictionary: lhs.position ?? [:]).isEqual(to: rhs.position ?? [:]) else { return false }
        return true
    }
}
