//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock: APIModel {

    /** The default portion of quality that will transfer from the infuser to the infusee item. (InfuserQuality - InfuseeQuality) * baseQualityTransferRatio = base quality transferred. */
    public var baseQualityTransferRatio: Float?

    /** As long as InfuserQuality > InfuseeQuality, the amount of quality bestowed is guaranteed to be at least this value, even if the transferRatio would dictate that it should be less. The total amount of quality that ends up in the Infusee cannot exceed the Infuser's quality however (for instance, if you infuse a 300 item with a 301 item and the minimum quality increment is 10, the infused item will not end up with 310 quality) */
    public var minimumQualityIncrement: Int?

    public init(baseQualityTransferRatio: Float? = nil, minimumQualityIncrement: Int? = nil) {
        self.baseQualityTransferRatio = baseQualityTransferRatio
        self.minimumQualityIncrement = minimumQualityIncrement
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        baseQualityTransferRatio = try container.decodeIfPresent("baseQualityTransferRatio")
        minimumQualityIncrement = try container.decodeIfPresent("minimumQualityIncrement")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(baseQualityTransferRatio, forKey: "baseQualityTransferRatio")
        try container.encodeIfPresent(minimumQualityIncrement, forKey: "minimumQualityIncrement")
    }

    public static func == (lhs: DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock, rhs: DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock) -> Bool {
        guard lhs.baseQualityTransferRatio == rhs.baseQualityTransferRatio else { return false }
        guard lhs.minimumQualityIncrement == rhs.minimumQualityIncrement else { return false }
        return true
    }
}
