//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Human readable data about the bubble. Combine with DestinyBubbleDefinition - see DestinyDestinationDefinition.bubbleSettings for more information.
DEPRECATED - Just use bubbles. */
public struct DestinyDefinitionsDestinyDestinationBubbleSettingDefinition: APIModel {

    public var displayProperties: DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition?

    public init(displayProperties: DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition? = nil) {
        self.displayProperties = displayProperties
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        displayProperties = try container.decodeIfPresent("displayProperties")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(displayProperties, forKey: "displayProperties")
    }

    public static func == (lhs: DestinyDefinitionsDestinyDestinationBubbleSettingDefinition, rhs: DestinyDefinitionsDestinyDestinationBubbleSettingDefinition) -> Bool {
        guard lhs.displayProperties == rhs.displayProperties else { return false }
        return true
    }
}
