//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Sockets on an item are organized into Categories visually.
You can find references to the socket category defined on an item's DestinyInventoryItemDefinition.sockets.socketCategories property.
This has the display information for rendering the categories' header, and a hint for how the UI should handle showing this category.
The shitty thing about this, however, is that the socket categories' UI style can be overridden by the item's UI style. For instance, the Socket Category used by Emote Sockets says it's "consumable," but that's a lie: they're all reusable, and overridden by the detail UI pages in ways that we can't easily account for in the API.
As a result, I will try to compile these rules into the individual sockets on items, and provide the best hint possible there through the plugSources property. In the future, I may attempt to use this information in conjunction with the item to provide a more usable UI hint on the socket layer, but for now improving the consistency of plugSources is the best I have time to provide. (See https://github.com/Bungie-net/api/issues/522 for more info) */
public struct DestinyDefinitionsSocketsDestinySocketCategoryDefinition: APIModel {

    /** Same as uiCategoryStyle, but in a more usable enumeration form. */
    public var categoryStyle: Int?

    public var displayProperties: DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition?

    /** The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
When entities refer to each other in Destiny content, it is this hash that they are referring to. */
    public var hash: Int?

    /** The index of the entity as it was found in the investment tables. */
    public var index: Int?

    /** If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry! */
    public var redacted: Bool?

    /** A string hinting to the game's UI system about how the sockets in this category should be displayed.
BNet doesn't use it: it's up to you to find valid values and make your own special UI if you want to honor this category style. */
    public var uiCategoryStyle: Int?

    public init(categoryStyle: Int? = nil, displayProperties: DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition? = nil, hash: Int? = nil, index: Int? = nil, redacted: Bool? = nil, uiCategoryStyle: Int? = nil) {
        self.categoryStyle = categoryStyle
        self.displayProperties = displayProperties
        self.hash = hash
        self.index = index
        self.redacted = redacted
        self.uiCategoryStyle = uiCategoryStyle
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        categoryStyle = try container.decodeIfPresent("categoryStyle")
        displayProperties = try container.decodeIfPresent("displayProperties")
        hash = try container.decodeIfPresent("hash")
        index = try container.decodeIfPresent("index")
        redacted = try container.decodeIfPresent("redacted")
        uiCategoryStyle = try container.decodeIfPresent("uiCategoryStyle")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(categoryStyle, forKey: "categoryStyle")
        try container.encodeIfPresent(displayProperties, forKey: "displayProperties")
        try container.encodeIfPresent(hash, forKey: "hash")
        try container.encodeIfPresent(index, forKey: "index")
        try container.encodeIfPresent(redacted, forKey: "redacted")
        try container.encodeIfPresent(uiCategoryStyle, forKey: "uiCategoryStyle")
    }

    public static func == (lhs: DestinyDefinitionsSocketsDestinySocketCategoryDefinition, rhs: DestinyDefinitionsSocketsDestinySocketCategoryDefinition) -> Bool {
        guard lhs.categoryStyle == rhs.categoryStyle else { return false }
        guard lhs.displayProperties == rhs.displayProperties else { return false }
        guard lhs.hash == rhs.hash else { return false }
        guard lhs.index == rhs.index else { return false }
        guard lhs.redacted == rhs.redacted else { return false }
        guard lhs.uiCategoryStyle == rhs.uiCategoryStyle else { return false }
        return true
    }
}
