//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Part of our dynamic, localized Milestone content is arbitrary categories of items. These are built in our content management system, and thus aren't the same as programmatically generated rewards. */
public struct DestinyMilestonesDestinyMilestoneContentItemCategory: APIModel {

    public var itemHashes: [Int]?

    public var title: String?

    public init(itemHashes: [Int]? = nil, title: String? = nil) {
        self.itemHashes = itemHashes
        self.title = title
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        itemHashes = try container.decodeArrayIfPresent("itemHashes")
        title = try container.decodeIfPresent("title")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(itemHashes, forKey: "itemHashes")
        try container.encodeIfPresent(title, forKey: "title")
    }

    public static func == (lhs: DestinyMilestonesDestinyMilestoneContentItemCategory, rhs: DestinyMilestonesDestinyMilestoneContentItemCategory) -> Bool {
        guard lhs.itemHashes == rhs.itemHashes else { return false }
        guard lhs.title == rhs.title else { return false }
        return true
    }
}
