//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsPresentationDestinyPresentationNodeChildEntry: APIModel {

    public var presentationNodeHash: Int?

    public init(presentationNodeHash: Int? = nil) {
        self.presentationNodeHash = presentationNodeHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        presentationNodeHash = try container.decodeIfPresent("presentationNodeHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(presentationNodeHash, forKey: "presentationNodeHash")
    }

    public static func == (lhs: DestinyDefinitionsPresentationDestinyPresentationNodeChildEntry, rhs: DestinyDefinitionsPresentationDestinyPresentationNodeChildEntry) -> Bool {
        guard lhs.presentationNodeHash == rhs.presentationNodeHash else { return false }
        return true
    }
}
