//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The information for how the vendor purchase should override a given socket with custom plug data. */
public struct DestinyDefinitionsDestinyVendorItemSocketOverride: APIModel {

    /** If this is greater than -1, the number of randomized plugs on this socket will be set to this quantity instead of whatever it's set to by default. */
    public var randomizedOptionsCount: Int?

    /** If this is populated, the socket will be overridden with a specific plug.
If this isn't populated, it's being overridden by something more complicated that is only known by the Game Server and God, which means we can't tell you in advance what it'll be. */
    public var singleItemHash: Int?

    /** This appears to be used to select which socket ultimately gets the override defined here. */
    public var socketTypeHash: Int?

    public init(randomizedOptionsCount: Int? = nil, singleItemHash: Int? = nil, socketTypeHash: Int? = nil) {
        self.randomizedOptionsCount = randomizedOptionsCount
        self.singleItemHash = singleItemHash
        self.socketTypeHash = socketTypeHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        randomizedOptionsCount = try container.decodeIfPresent("randomizedOptionsCount")
        singleItemHash = try container.decodeIfPresent("singleItemHash")
        socketTypeHash = try container.decodeIfPresent("socketTypeHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(randomizedOptionsCount, forKey: "randomizedOptionsCount")
        try container.encodeIfPresent(singleItemHash, forKey: "singleItemHash")
        try container.encodeIfPresent(socketTypeHash, forKey: "socketTypeHash")
    }

    public static func == (lhs: DestinyDefinitionsDestinyVendorItemSocketOverride, rhs: DestinyDefinitionsDestinyVendorItemSocketOverride) -> Bool {
        guard lhs.randomizedOptionsCount == rhs.randomizedOptionsCount else { return false }
        guard lhs.singleItemHash == rhs.singleItemHash else { return false }
        guard lhs.socketTypeHash == rhs.socketTypeHash else { return false }
        return true
    }
}
