//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** An overly complicated wrapper for the item level at which the item should spawn. */
public struct DestinyDefinitionsDestinyItemCreationEntryLevelDefinition: APIModel {

    public var level: Int?

    public init(level: Int? = nil) {
        self.level = level
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        level = try container.decodeIfPresent("level")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(level, forKey: "level")
    }

    public static func == (lhs: DestinyDefinitionsDestinyItemCreationEntryLevelDefinition, rhs: DestinyDefinitionsDestinyItemCreationEntryLevelDefinition) -> Bool {
        guard lhs.level == rhs.level else { return false }
        return true
    }
}
