//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyItemComponentSetOfint32: APIModel {

    public var instances: DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent?

    public var objectives: DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent?

    public var perks: DictionaryComponentResponseOfint32AndDestinyItemPerksComponent?

    public var plugObjectives: DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent?

    public var plugStates: DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent?

    public var renderData: DictionaryComponentResponseOfint32AndDestinyItemRenderComponent?

    public var reusablePlugs: DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent?

    public var sockets: DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent?

    public var stats: DictionaryComponentResponseOfint32AndDestinyItemStatsComponent?

    public var talentGrids: DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent?

    public init(instances: DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent? = nil, objectives: DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent? = nil, perks: DictionaryComponentResponseOfint32AndDestinyItemPerksComponent? = nil, plugObjectives: DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent? = nil, plugStates: DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent? = nil, renderData: DictionaryComponentResponseOfint32AndDestinyItemRenderComponent? = nil, reusablePlugs: DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent? = nil, sockets: DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent? = nil, stats: DictionaryComponentResponseOfint32AndDestinyItemStatsComponent? = nil, talentGrids: DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent? = nil) {
        self.instances = instances
        self.objectives = objectives
        self.perks = perks
        self.plugObjectives = plugObjectives
        self.plugStates = plugStates
        self.renderData = renderData
        self.reusablePlugs = reusablePlugs
        self.sockets = sockets
        self.stats = stats
        self.talentGrids = talentGrids
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        instances = try container.decodeIfPresent("instances")
        objectives = try container.decodeIfPresent("objectives")
        perks = try container.decodeIfPresent("perks")
        plugObjectives = try container.decodeIfPresent("plugObjectives")
        plugStates = try container.decodeIfPresent("plugStates")
        renderData = try container.decodeIfPresent("renderData")
        reusablePlugs = try container.decodeIfPresent("reusablePlugs")
        sockets = try container.decodeIfPresent("sockets")
        stats = try container.decodeIfPresent("stats")
        talentGrids = try container.decodeIfPresent("talentGrids")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(instances, forKey: "instances")
        try container.encodeIfPresent(objectives, forKey: "objectives")
        try container.encodeIfPresent(perks, forKey: "perks")
        try container.encodeIfPresent(plugObjectives, forKey: "plugObjectives")
        try container.encodeIfPresent(plugStates, forKey: "plugStates")
        try container.encodeIfPresent(renderData, forKey: "renderData")
        try container.encodeIfPresent(reusablePlugs, forKey: "reusablePlugs")
        try container.encodeIfPresent(sockets, forKey: "sockets")
        try container.encodeIfPresent(stats, forKey: "stats")
        try container.encodeIfPresent(talentGrids, forKey: "talentGrids")
    }

    public static func == (lhs: DestinyItemComponentSetOfint32, rhs: DestinyItemComponentSetOfint32) -> Bool {
        guard lhs.instances == rhs.instances else { return false }
        guard lhs.objectives == rhs.objectives else { return false }
        guard lhs.perks == rhs.perks else { return false }
        guard lhs.plugObjectives == rhs.plugObjectives else { return false }
        guard lhs.plugStates == rhs.plugStates else { return false }
        guard lhs.renderData == rhs.renderData else { return false }
        guard lhs.reusablePlugs == rhs.reusablePlugs else { return false }
        guard lhs.sockets == rhs.sockets else { return false }
        guard lhs.stats == rhs.stats else { return false }
        guard lhs.talentGrids == rhs.talentGrids else { return false }
        return true
    }
}
