//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The results of a bulk Equipping operation performed through the Destiny API. */
public struct DestinyDestinyEquipItemResults: APIModel {

    public var equipResults: [DestinyDestinyEquipItemResult]?

    public init(equipResults: [DestinyDestinyEquipItemResult]? = nil) {
        self.equipResults = equipResults
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        equipResults = try container.decodeArrayIfPresent("equipResults")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(equipResults, forKey: "equipResults")
    }

    public static func == (lhs: DestinyDestinyEquipItemResults, rhs: DestinyDestinyEquipItemResults) -> Bool {
        guard lhs.equipResults == rhs.equipResults else { return false }
        return true
    }
}
