//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The response for GetDestinyProfile, with components for character and item-level data. */
public struct DestinyResponsesDestinyProfileResponse: APIModel {

    /** Character activity data - the activities available to this character and its status, keyed by the Character's Id.
COMPONENT TYPE: CharacterActivities */
    public var characterActivities: [String: Any]?

    /** COMPONENT TYPE: Collectibles */
    public var characterCollectibles: [String: Any]?

    /** A "lookup" convenience component that can be used to quickly check if the character has access to items that can be used for purchasing.
COMPONENT TYPE: CurrencyLookups */
    public var characterCurrencyLookups: [String: Any]?

    /** The character's equipped items, keyed by the Character's Id.
COMPONENT TYPE: CharacterEquipment */
    public var characterEquipment: [String: Any]?

    /** The character-level non-equipped inventory items, keyed by the Character's Id.
COMPONENT TYPE: CharacterInventories */
    public var characterInventories: [String: Any]?

    /** Items available from Kiosks that are available to a specific character as opposed to the account as a whole. It must be combined with data from the profileKiosks property to get a full picture of the character's available items to check out of a kiosk.
This component returns information about what Kiosk items are available to you on a *Character* level. Usually, kiosk items will be earned for the entire Profile (all characters) at once. To find those, look in the profileKiosks property.
COMPONENT TYPE: Kiosks */
    public var characterKiosks: [String: Any]?

    /** When sockets refer to reusable Plug Sets (see DestinyPlugSetDefinition for more info), this is the set of plugs and their states, per character, that are character-scoped.
This comes back with ItemSockets, as it is needed for a complete picture of the sockets on requested items.
COMPONENT TYPE: ItemSockets */
    public var characterPlugSets: [String: Any]?

    /** COMPONENT TYPE: PresentationNodes */
    public var characterPresentationNodes: [String: Any]?

    /** Character-level progression data, keyed by the Character's Id.
COMPONENT TYPE: CharacterProgressions */
    public var characterProgressions: [String: Any]?

    /** COMPONENT TYPE: Records */
    public var characterRecords: [String: Any]?

    /** Character rendering data - a minimal set of info needed to render a character in 3D - keyed by the Character's Id.
COMPONENT TYPE: CharacterRenderData */
    public var characterRenderData: [String: Any]?

    /** Do you ever get the feeling that a system was designed *too* flexibly? That it can be used in so many different ways that you end up being unable to provide an easy to use abstraction for the mess that's happening under the surface?
Let's talk about character-specific data that might be related to items without instances. These two statements are totally unrelated, I promise.
At some point during D2, it was decided that items - such as Bounties - could be given to characters and *not* have instance data, but that *could* display and even use relevant state information on your account and character.
Up to now, any item that had meaningful dependencies on character or account state had to be instanced, and thus "itemComponents" was all that you needed: it was keyed by item's instance IDs and provided the stateful information you needed inside.
Unfortunately, we don't live in such a magical world anymore. This is information held on a per-character basis about non-instanced items that the characters have in their inventory - or that reference character-specific state information even if it's in Account-level inventory - and the values related to that item's state in relation to the given character.
To give a concrete example, look at a Moments of Triumph bounty. They exist in a character's inventory, and show/care about a character's progression toward completing the bounty. But the bounty itself is a non-instanced item, like a mod or a currency. This returns that data for the characters who have the bounty in their inventory.
I'm not crying, you're crying Okay we're both crying but it's going to be okay I promise Actually I shouldn't promise that, I don't know if it's going to be okay */
    public var characterUninstancedItemComponents: [String: DestinyBaseItemComponentSetOfuint32]?

    /** Basic information about each character, keyed by the CharacterId.
COMPONENT TYPE: Characters */
    public var characters: [String: Any]?

    /** Information about instanced items across all returned characters, keyed by the item's instance ID.
COMPONENT TYPE: [See inside the DestinyItemComponentSet contract for component types.] */
    public var itemComponents: [String: Any]?

    /** Silver quantities for any platform on which this Profile plays destiny.
 COMPONENT TYPE: PlatformSilver */
    public var platformSilver: [String: Any]?

    /** The basic information about the Destiny Profile (formerly "Account").
COMPONENT TYPE: Profiles */
    public var profile: [String: Any]?

    /** COMPONENT TYPE: Collectibles */
    public var profileCollectibles: [String: Any]?

    /** The profile-level currencies owned by the Destiny Profile.
COMPONENT TYPE: ProfileCurrencies */
    public var profileCurrencies: [String: Any]?

    /** The profile-level inventory of the Destiny Profile.
COMPONENT TYPE: ProfileInventories */
    public var profileInventory: [String: Any]?

    /** Items available from Kiosks that are available Profile-wide (i.e. across all characters)
This component returns information about what Kiosk items are available to you on a *Profile* level. It is theoretically possible for Kiosks to have items gated by specific Character as well. If you ever have those, you will find them on the characterKiosks property.
COMPONENT TYPE: Kiosks */
    public var profileKiosks: [String: Any]?

    /** When sockets refer to reusable Plug Sets (see DestinyPlugSetDefinition for more info), this is the set of plugs and their states that are profile-scoped.
This comes back with ItemSockets, as it is needed for a complete picture of the sockets on requested items.
COMPONENT TYPE: ItemSockets */
    public var profilePlugSets: [String: Any]?

    /** COMPONENT TYPE: PresentationNodes */
    public var profilePresentationNodes: [String: Any]?

    /** When we have progression information - such as Checklists - that may apply profile-wide, it will be returned here rather than in the per-character progression data.
COMPONENT TYPE: ProfileProgression */
    public var profileProgression: [String: Any]?

    /** COMPONENT TYPE: Records */
    public var profileRecords: [String: Any]?

    /** COMPONENT TYPE: Transitory */
    public var profileTransitoryData: [String: Any]?

    /** Recent, refundable purchases you have made from vendors. When will you use it? Couldn't say...
COMPONENT TYPE: VendorReceipts */
    public var vendorReceipts: [String: Any]?

    public init(characterActivities: [String: Any]? = nil, characterCollectibles: [String: Any]? = nil, characterCurrencyLookups: [String: Any]? = nil, characterEquipment: [String: Any]? = nil, characterInventories: [String: Any]? = nil, characterKiosks: [String: Any]? = nil, characterPlugSets: [String: Any]? = nil, characterPresentationNodes: [String: Any]? = nil, characterProgressions: [String: Any]? = nil, characterRecords: [String: Any]? = nil, characterRenderData: [String: Any]? = nil, characterUninstancedItemComponents: [String: DestinyBaseItemComponentSetOfuint32]? = nil, characters: [String: Any]? = nil, itemComponents: [String: Any]? = nil, platformSilver: [String: Any]? = nil, profile: [String: Any]? = nil, profileCollectibles: [String: Any]? = nil, profileCurrencies: [String: Any]? = nil, profileInventory: [String: Any]? = nil, profileKiosks: [String: Any]? = nil, profilePlugSets: [String: Any]? = nil, profilePresentationNodes: [String: Any]? = nil, profileProgression: [String: Any]? = nil, profileRecords: [String: Any]? = nil, profileTransitoryData: [String: Any]? = nil, vendorReceipts: [String: Any]? = nil) {
        self.characterActivities = characterActivities
        self.characterCollectibles = characterCollectibles
        self.characterCurrencyLookups = characterCurrencyLookups
        self.characterEquipment = characterEquipment
        self.characterInventories = characterInventories
        self.characterKiosks = characterKiosks
        self.characterPlugSets = characterPlugSets
        self.characterPresentationNodes = characterPresentationNodes
        self.characterProgressions = characterProgressions
        self.characterRecords = characterRecords
        self.characterRenderData = characterRenderData
        self.characterUninstancedItemComponents = characterUninstancedItemComponents
        self.characters = characters
        self.itemComponents = itemComponents
        self.platformSilver = platformSilver
        self.profile = profile
        self.profileCollectibles = profileCollectibles
        self.profileCurrencies = profileCurrencies
        self.profileInventory = profileInventory
        self.profileKiosks = profileKiosks
        self.profilePlugSets = profilePlugSets
        self.profilePresentationNodes = profilePresentationNodes
        self.profileProgression = profileProgression
        self.profileRecords = profileRecords
        self.profileTransitoryData = profileTransitoryData
        self.vendorReceipts = vendorReceipts
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        characterActivities = try container.decodeAnyIfPresent("characterActivities")
        characterCollectibles = try container.decodeAnyIfPresent("characterCollectibles")
        characterCurrencyLookups = try container.decodeAnyIfPresent("characterCurrencyLookups")
        characterEquipment = try container.decodeAnyIfPresent("characterEquipment")
        characterInventories = try container.decodeAnyIfPresent("characterInventories")
        characterKiosks = try container.decodeAnyIfPresent("characterKiosks")
        characterPlugSets = try container.decodeAnyIfPresent("characterPlugSets")
        characterPresentationNodes = try container.decodeAnyIfPresent("characterPresentationNodes")
        characterProgressions = try container.decodeAnyIfPresent("characterProgressions")
        characterRecords = try container.decodeAnyIfPresent("characterRecords")
        characterRenderData = try container.decodeAnyIfPresent("characterRenderData")
        characterUninstancedItemComponents = try container.decodeIfPresent("characterUninstancedItemComponents")
        characters = try container.decodeAnyIfPresent("characters")
        itemComponents = try container.decodeAnyIfPresent("itemComponents")
        platformSilver = try container.decodeAnyIfPresent("platformSilver")
        profile = try container.decodeAnyIfPresent("profile")
        profileCollectibles = try container.decodeAnyIfPresent("profileCollectibles")
        profileCurrencies = try container.decodeAnyIfPresent("profileCurrencies")
        profileInventory = try container.decodeAnyIfPresent("profileInventory")
        profileKiosks = try container.decodeAnyIfPresent("profileKiosks")
        profilePlugSets = try container.decodeAnyIfPresent("profilePlugSets")
        profilePresentationNodes = try container.decodeAnyIfPresent("profilePresentationNodes")
        profileProgression = try container.decodeAnyIfPresent("profileProgression")
        profileRecords = try container.decodeAnyIfPresent("profileRecords")
        profileTransitoryData = try container.decodeAnyIfPresent("profileTransitoryData")
        vendorReceipts = try container.decodeAnyIfPresent("vendorReceipts")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeAnyIfPresent(characterActivities, forKey: "characterActivities")
        try container.encodeAnyIfPresent(characterCollectibles, forKey: "characterCollectibles")
        try container.encodeAnyIfPresent(characterCurrencyLookups, forKey: "characterCurrencyLookups")
        try container.encodeAnyIfPresent(characterEquipment, forKey: "characterEquipment")
        try container.encodeAnyIfPresent(characterInventories, forKey: "characterInventories")
        try container.encodeAnyIfPresent(characterKiosks, forKey: "characterKiosks")
        try container.encodeAnyIfPresent(characterPlugSets, forKey: "characterPlugSets")
        try container.encodeAnyIfPresent(characterPresentationNodes, forKey: "characterPresentationNodes")
        try container.encodeAnyIfPresent(characterProgressions, forKey: "characterProgressions")
        try container.encodeAnyIfPresent(characterRecords, forKey: "characterRecords")
        try container.encodeAnyIfPresent(characterRenderData, forKey: "characterRenderData")
        try container.encodeIfPresent(characterUninstancedItemComponents, forKey: "characterUninstancedItemComponents")
        try container.encodeAnyIfPresent(characters, forKey: "characters")
        try container.encodeAnyIfPresent(itemComponents, forKey: "itemComponents")
        try container.encodeAnyIfPresent(platformSilver, forKey: "platformSilver")
        try container.encodeAnyIfPresent(profile, forKey: "profile")
        try container.encodeAnyIfPresent(profileCollectibles, forKey: "profileCollectibles")
        try container.encodeAnyIfPresent(profileCurrencies, forKey: "profileCurrencies")
        try container.encodeAnyIfPresent(profileInventory, forKey: "profileInventory")
        try container.encodeAnyIfPresent(profileKiosks, forKey: "profileKiosks")
        try container.encodeAnyIfPresent(profilePlugSets, forKey: "profilePlugSets")
        try container.encodeAnyIfPresent(profilePresentationNodes, forKey: "profilePresentationNodes")
        try container.encodeAnyIfPresent(profileProgression, forKey: "profileProgression")
        try container.encodeAnyIfPresent(profileRecords, forKey: "profileRecords")
        try container.encodeAnyIfPresent(profileTransitoryData, forKey: "profileTransitoryData")
        try container.encodeAnyIfPresent(vendorReceipts, forKey: "vendorReceipts")
    }

    public static func == (lhs: DestinyResponsesDestinyProfileResponse, rhs: DestinyResponsesDestinyProfileResponse) -> Bool {
        guard NSDictionary(dictionary: lhs.characterActivities ?? [:]).isEqual(to: rhs.characterActivities ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterCollectibles ?? [:]).isEqual(to: rhs.characterCollectibles ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterCurrencyLookups ?? [:]).isEqual(to: rhs.characterCurrencyLookups ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterEquipment ?? [:]).isEqual(to: rhs.characterEquipment ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterInventories ?? [:]).isEqual(to: rhs.characterInventories ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterKiosks ?? [:]).isEqual(to: rhs.characterKiosks ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterPlugSets ?? [:]).isEqual(to: rhs.characterPlugSets ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterPresentationNodes ?? [:]).isEqual(to: rhs.characterPresentationNodes ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterProgressions ?? [:]).isEqual(to: rhs.characterProgressions ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterRecords ?? [:]).isEqual(to: rhs.characterRecords ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.characterRenderData ?? [:]).isEqual(to: rhs.characterRenderData ?? [:]) else { return false }
        guard lhs.characterUninstancedItemComponents == rhs.characterUninstancedItemComponents else { return false }
        guard NSDictionary(dictionary: lhs.characters ?? [:]).isEqual(to: rhs.characters ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.itemComponents ?? [:]).isEqual(to: rhs.itemComponents ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.platformSilver ?? [:]).isEqual(to: rhs.platformSilver ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profile ?? [:]).isEqual(to: rhs.profile ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profileCollectibles ?? [:]).isEqual(to: rhs.profileCollectibles ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profileCurrencies ?? [:]).isEqual(to: rhs.profileCurrencies ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profileInventory ?? [:]).isEqual(to: rhs.profileInventory ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profileKiosks ?? [:]).isEqual(to: rhs.profileKiosks ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profilePlugSets ?? [:]).isEqual(to: rhs.profilePlugSets ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profilePresentationNodes ?? [:]).isEqual(to: rhs.profilePresentationNodes ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profileProgression ?? [:]).isEqual(to: rhs.profileProgression ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profileRecords ?? [:]).isEqual(to: rhs.profileRecords ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.profileTransitoryData ?? [:]).isEqual(to: rhs.profileTransitoryData ?? [:]) else { return false }
        guard NSDictionary(dictionary: lhs.vendorReceipts ?? [:]).isEqual(to: rhs.vendorReceipts ?? [:]) else { return false }
        return true
    }
}
