//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum DestinyDefinitionsDestinyTalentNodeStepDamageTypes: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case _4 = 4
    case _8 = 8
    case _15 = 15
}
