//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Represents the different kinds of acquisition behavior for progression reward items. */
/** Represents the different kinds of acquisition behavior for progression reward items. */
public enum DestinyDestinyProgressionRewardItemAcquisitionBehavior: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
