//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData: APIModel {

    /** Collection of stats for the player in this activity. */
    public var values: [String: DestinyHistoricalStatsDestinyHistoricalStatsValue]?

    /** List of weapons and their perspective values. */
    public var weapons: [DestinyHistoricalStatsDestinyHistoricalWeaponStats]?

    public init(values: [String: DestinyHistoricalStatsDestinyHistoricalStatsValue]? = nil, weapons: [DestinyHistoricalStatsDestinyHistoricalWeaponStats]? = nil) {
        self.values = values
        self.weapons = weapons
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        values = try container.decodeIfPresent("values")
        weapons = try container.decodeArrayIfPresent("weapons")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(values, forKey: "values")
        try container.encodeIfPresent(weapons, forKey: "weapons")
    }

    public static func == (lhs: DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData, rhs: DestinyHistoricalStatsDestinyPostGameCarnageReportExtendedData) -> Bool {
        guard lhs.values == rhs.values else { return false }
        guard lhs.weapons == rhs.weapons else { return false }
        return true
    }
}
