//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The list of indexes into the Talent Grid's "nodes" property for nodes in this exclusive set. (See DestinyTalentNodeDefinition.nodeIndex) */
public struct DestinyDefinitionsDestinyTalentNodeExclusiveSetDefinition: APIModel {

    /** The list of node indexes for the exclusive set. Historically, these were indexes. I would have liked to replace this with nodeHashes for consistency, but it's way too late for that. (9:09 PM, he's right!) */
    public var nodeIndexes: [Int]?

    public init(nodeIndexes: [Int]? = nil) {
        self.nodeIndexes = nodeIndexes
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        nodeIndexes = try container.decodeArrayIfPresent("nodeIndexes")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(nodeIndexes, forKey: "nodeIndexes")
    }

    public static func == (lhs: DestinyDefinitionsDestinyTalentNodeExclusiveSetDefinition, rhs: DestinyDefinitionsDestinyTalentNodeExclusiveSetDefinition) -> Bool {
        guard lhs.nodeIndexes == rhs.nodeIndexes else { return false }
        return true
    }
}
