//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Display categories can have custom sort orders. These are the possible options. */
/** Display categories can have custom sort orders. These are the possible options. */
public enum DestinyVendorDisplayCategorySortOrder: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
