//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Instanced items can have perks: benefits that the item bestows.
These are related to DestinySandboxPerkDefinition, and sometimes - but not always - have human readable info. When they do, they are the icons and text that you see in an item's tooltip.
Talent Grids, Sockets, and the item itself can apply Perks, which are then summarized here for your convenience. */
public struct DestinyEntitiesItemsDestinyItemPerksComponent: APIModel {

    /** The list of perks to display in an item tooltip - and whether or not they have been activated. */
    public var perks: [DestinyPerksDestinyPerkReference]?

    public init(perks: [DestinyPerksDestinyPerkReference]? = nil) {
        self.perks = perks
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        perks = try container.decodeArrayIfPresent("perks")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(perks, forKey: "perks")
    }

    public static func == (lhs: DestinyEntitiesItemsDestinyItemPerksComponent, rhs: DestinyEntitiesItemsDestinyItemPerksComponent) -> Bool {
        guard lhs.perks == rhs.perks else { return false }
        return true
    }
}
