//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** On to one of the more confusing subjects of the API. What is a Destination, and what is the relationship between it, Activities, Locations, and Places?
A "Destination" is a specific region/city/area of a larger "Place". For instance, a Place might be Earth where a Destination might be Bellevue, Washington. (Please, pick a more interesting destination if you come to visit Earth). */
public struct DestinyDefinitionsDestinyDestinationDefinition: APIModel {

    /** If the Destination has default Activity Graphs (i.e. "Map") that should be shown in the director, this is the list of those Graphs. At most, only one should be active at any given time for a Destination: these would represent, for example, different variants on a Map if the Destination is changing on a macro level based on game state. */
    public var activityGraphEntries: [DestinyDefinitionsDestinyActivityGraphListEntryDefinition]?

    /** A Destination may have many "Bubbles" zones with human readable properties.
We don't get as much info as I'd like about them - I'd love to return info like where on the map they are located - but at least this gives you the name of those bubbles. bubbleSettings and bubbles both have the identical number of entries, and you should match up their indexes to provide matching bubble and bubbleSettings data.
DEPRECATED - Just use bubbles, it now has this data. */
    public var bubbleSettings: [DestinyDefinitionsDestinyDestinationBubbleSettingDefinition]?

    /** This provides the unique identifiers for every bubble in the destination (only guaranteed unique within the destination), and any intrinsic properties of the bubble.
bubbleSettings and bubbles both have the identical number of entries, and you should match up their indexes to provide matching bubble and bubbleSettings data. */
    public var bubbles: [DestinyDefinitionsDestinyBubbleDefinition]?

    /** If this Destination has a default Free-Roam activity, this is the hash for that Activity. Use it to look up the DestinyActivityDefintion. */
    public var defaultFreeroamActivityHash: Int?

    public var displayProperties: DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition?

    /** The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
When entities refer to each other in Destiny content, it is this hash that they are referring to. */
    public var hash: Int?

    /** The index of the entity as it was found in the investment tables. */
    public var index: Int?

    /** The place that "owns" this Destination. Use this hash to look up the DestinyPlaceDefinition. */
    public var placeHash: Int?

    /** If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry! */
    public var redacted: Bool?

    public init(activityGraphEntries: [DestinyDefinitionsDestinyActivityGraphListEntryDefinition]? = nil, bubbleSettings: [DestinyDefinitionsDestinyDestinationBubbleSettingDefinition]? = nil, bubbles: [DestinyDefinitionsDestinyBubbleDefinition]? = nil, defaultFreeroamActivityHash: Int? = nil, displayProperties: DestinyDefinitionsCommonDestinyDisplayPropertiesDefinition? = nil, hash: Int? = nil, index: Int? = nil, placeHash: Int? = nil, redacted: Bool? = nil) {
        self.activityGraphEntries = activityGraphEntries
        self.bubbleSettings = bubbleSettings
        self.bubbles = bubbles
        self.defaultFreeroamActivityHash = defaultFreeroamActivityHash
        self.displayProperties = displayProperties
        self.hash = hash
        self.index = index
        self.placeHash = placeHash
        self.redacted = redacted
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        activityGraphEntries = try container.decodeArrayIfPresent("activityGraphEntries")
        bubbleSettings = try container.decodeArrayIfPresent("bubbleSettings")
        bubbles = try container.decodeArrayIfPresent("bubbles")
        defaultFreeroamActivityHash = try container.decodeIfPresent("defaultFreeroamActivityHash")
        displayProperties = try container.decodeIfPresent("displayProperties")
        hash = try container.decodeIfPresent("hash")
        index = try container.decodeIfPresent("index")
        placeHash = try container.decodeIfPresent("placeHash")
        redacted = try container.decodeIfPresent("redacted")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(activityGraphEntries, forKey: "activityGraphEntries")
        try container.encodeIfPresent(bubbleSettings, forKey: "bubbleSettings")
        try container.encodeIfPresent(bubbles, forKey: "bubbles")
        try container.encodeIfPresent(defaultFreeroamActivityHash, forKey: "defaultFreeroamActivityHash")
        try container.encodeIfPresent(displayProperties, forKey: "displayProperties")
        try container.encodeIfPresent(hash, forKey: "hash")
        try container.encodeIfPresent(index, forKey: "index")
        try container.encodeIfPresent(placeHash, forKey: "placeHash")
        try container.encodeIfPresent(redacted, forKey: "redacted")
    }

    public static func == (lhs: DestinyDefinitionsDestinyDestinationDefinition, rhs: DestinyDefinitionsDestinyDestinationDefinition) -> Bool {
        guard lhs.activityGraphEntries == rhs.activityGraphEntries else { return false }
        guard lhs.bubbleSettings == rhs.bubbleSettings else { return false }
        guard lhs.bubbles == rhs.bubbles else { return false }
        guard lhs.defaultFreeroamActivityHash == rhs.defaultFreeroamActivityHash else { return false }
        guard lhs.displayProperties == rhs.displayProperties else { return false }
        guard lhs.hash == rhs.hash else { return false }
        guard lhs.index == rhs.index else { return false }
        guard lhs.placeHash == rhs.placeHash else { return false }
        guard lhs.redacted == rhs.redacted else { return false }
        return true
    }
}
