//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDyeReference: APIModel {

    public var channelHash: Int?

    public var dyeHash: Int?

    public init(channelHash: Int? = nil, dyeHash: Int? = nil) {
        self.channelHash = channelHash
        self.dyeHash = dyeHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        channelHash = try container.decodeIfPresent("channelHash")
        dyeHash = try container.decodeIfPresent("dyeHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(channelHash, forKey: "channelHash")
        try container.encodeIfPresent(dyeHash, forKey: "dyeHash")
    }

    public static func == (lhs: DestinyDyeReference, rhs: DestinyDyeReference) -> Bool {
        guard lhs.channelHash == rhs.channelHash else { return false }
        guard lhs.dyeHash == rhs.dyeHash else { return false }
        return true
    }
}
