//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsDestinyActivityLoadoutRequirementSet: APIModel {

    /** The set of requirements that will be applied on the activity if this requirement set is active. */
    public var requirements: [DestinyDefinitionsDestinyActivityLoadoutRequirement]?

    public init(requirements: [DestinyDefinitionsDestinyActivityLoadoutRequirement]? = nil) {
        self.requirements = requirements
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        requirements = try container.decodeArrayIfPresent("requirements")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(requirements, forKey: "requirements")
    }

    public static func == (lhs: DestinyDefinitionsDestinyActivityLoadoutRequirementSet, rhs: DestinyDefinitionsDestinyActivityLoadoutRequirementSet) -> Bool {
        guard lhs.requirements == rhs.requirements else { return false }
        return true
    }
}
