//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** If rewards are given in a quest - as opposed to overall in the entire Milestone - there's way less to track. We're going to simplify this contract as a result. However, this also gives us the opportunity to potentially put more than just item information into the reward data if we're able to mine it out in the future. Remember this if you come back and ask "why are quest reward items nested inside of their own class?" */
public struct DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardsDefinition: APIModel {

    /** The items that represent your reward for completing the quest.
Be warned, these could be "dummy" items: items that are only used to render a good-looking in-game tooltip, but aren't the actual items themselves.
For instance, when experience is given there's often a dummy item representing "experience", with quantity being the amount of experience you got. We don't have a programmatic association between those and whatever Progression is actually getting that experience... yet. */
    public var items: [DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem]?

    public init(items: [DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem]? = nil) {
        self.items = items
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        items = try container.decodeArrayIfPresent("items")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(items, forKey: "items")
    }

    public static func == (lhs: DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardsDefinition, rhs: DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardsDefinition) -> Bool {
        guard lhs.items == rhs.items else { return false }
        return true
    }
}
