//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsDestinyObjectiveDisplayProperties: APIModel {

    /** The activity associated with this objective in the context of this item, if any. */
    public var activityHash: Int?

    /** If true, the game shows this objective on item preview screens. */
    public var displayOnItemPreviewScreen: Bool?

    public init(activityHash: Int? = nil, displayOnItemPreviewScreen: Bool? = nil) {
        self.activityHash = activityHash
        self.displayOnItemPreviewScreen = displayOnItemPreviewScreen
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        activityHash = try container.decodeIfPresent("activityHash")
        displayOnItemPreviewScreen = try container.decodeIfPresent("displayOnItemPreviewScreen")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(activityHash, forKey: "activityHash")
        try container.encodeIfPresent(displayOnItemPreviewScreen, forKey: "displayOnItemPreviewScreen")
    }

    public static func == (lhs: DestinyDefinitionsDestinyObjectiveDisplayProperties, rhs: DestinyDefinitionsDestinyObjectiveDisplayProperties) -> Bool {
        guard lhs.activityHash == rhs.activityHash else { return false }
        guard lhs.displayOnItemPreviewScreen == rhs.displayOnItemPreviewScreen else { return false }
        return true
    }
}
