//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither. */
/** If progression is earned, this determines whether the progression shows visual effects on the character or its item - or neither. */
public enum DestinyDestinyProgressionStepDisplayEffect: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
