//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyComponentsPresentationDestinyPresentationNodesComponent: APIModel {

    public var nodes: [String: DestinyComponentsPresentationDestinyPresentationNodeComponent]?

    public init(nodes: [String: DestinyComponentsPresentationDestinyPresentationNodeComponent]? = nil) {
        self.nodes = nodes
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        nodes = try container.decodeIfPresent("nodes")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(nodes, forKey: "nodes")
    }

    public static func == (lhs: DestinyComponentsPresentationDestinyPresentationNodesComponent, rhs: DestinyComponentsPresentationDestinyPresentationNodesComponent) -> Bool {
        guard lhs.nodes == rhs.nodes else { return false }
        return true
    }
}
