//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyComponentsRecordsDestinyCharacterRecordsComponent: APIModel {

    public var featuredRecordHashes: [Int]?

    public var records: [String: DestinyComponentsRecordsDestinyRecordComponent]?

    public init(featuredRecordHashes: [Int]? = nil, records: [String: DestinyComponentsRecordsDestinyRecordComponent]? = nil) {
        self.featuredRecordHashes = featuredRecordHashes
        self.records = records
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        featuredRecordHashes = try container.decodeArrayIfPresent("featuredRecordHashes")
        records = try container.decodeIfPresent("records")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(featuredRecordHashes, forKey: "featuredRecordHashes")
        try container.encodeIfPresent(records, forKey: "records")
    }

    public static func == (lhs: DestinyComponentsRecordsDestinyCharacterRecordsComponent, rhs: DestinyComponentsRecordsDestinyCharacterRecordsComponent) -> Bool {
        guard lhs.featuredRecordHashes == rhs.featuredRecordHashes else { return false }
        guard lhs.records == rhs.records else { return false }
        return true
    }
}
