//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyComponentsRecordsDestinyProfileRecordsComponent: APIModel {

    public var records: [String: DestinyComponentsRecordsDestinyRecordComponent]?

    /** Your "Triumphs" score. */
    public var score: Int?

    /** If this profile is tracking a record, this is the hash identifier of the record it is tracking. */
    public var trackedRecordHash: Int?

    public init(records: [String: DestinyComponentsRecordsDestinyRecordComponent]? = nil, score: Int? = nil, trackedRecordHash: Int? = nil) {
        self.records = records
        self.score = score
        self.trackedRecordHash = trackedRecordHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        records = try container.decodeIfPresent("records")
        score = try container.decodeIfPresent("score")
        trackedRecordHash = try container.decodeIfPresent("trackedRecordHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(records, forKey: "records")
        try container.encodeIfPresent(score, forKey: "score")
        try container.encodeIfPresent(trackedRecordHash, forKey: "trackedRecordHash")
    }

    public static func == (lhs: DestinyComponentsRecordsDestinyProfileRecordsComponent, rhs: DestinyComponentsRecordsDestinyProfileRecordsComponent) -> Bool {
        guard lhs.records == rhs.records else { return false }
        guard lhs.score == rhs.score else { return false }
        guard lhs.trackedRecordHash == rhs.trackedRecordHash else { return false }
        return true
    }
}
