//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The action that happens when the user attempts to refund an item. */
/** The action that happens when the user attempts to refund an item. */
public enum DestinyDestinyVendorItemRefundPolicy: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
