//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyComponentsRecordsDestinyRecordsComponent: APIModel {

    public var records: [String: DestinyComponentsRecordsDestinyRecordComponent]?

    public init(records: [String: DestinyComponentsRecordsDestinyRecordComponent]? = nil) {
        self.records = records
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        records = try container.decodeIfPresent("records")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(records, forKey: "records")
    }

    public static func == (lhs: DestinyComponentsRecordsDestinyRecordsComponent, rhs: DestinyComponentsRecordsDestinyRecordsComponent) -> Bool {
        guard lhs.records == rhs.records else { return false }
        return true
    }
}
