//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Indicates the type of actions that can be performed */
/** Indicates the type of actions that can be performed */
public enum DestinySocketTypeActionType: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
