//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsPresentationDestinyPresentationNodeRecordChildEntry: APIModel {

    public var recordHash: Int?

    public init(recordHash: Int? = nil) {
        self.recordHash = recordHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        recordHash = try container.decodeIfPresent("recordHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(recordHash, forKey: "recordHash")
    }

    public static func == (lhs: DestinyDefinitionsPresentationDestinyPresentationNodeRecordChildEntry, rhs: DestinyDefinitionsPresentationDestinyPresentationNodeRecordChildEntry) -> Bool {
        guard lhs.recordHash == rhs.recordHash else { return false }
        return true
    }
}
