//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** When a Graph needs to show active Progressions, this defines those objectives as well as an identifier. */
public struct DestinyDefinitionsDirectorDestinyActivityGraphDisplayProgressionDefinition: APIModel {

    public var id: Int?

    public var progressionHash: Int?

    public init(id: Int? = nil, progressionHash: Int? = nil) {
        self.id = id
        self.progressionHash = progressionHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decodeIfPresent("id")
        progressionHash = try container.decodeIfPresent("progressionHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(progressionHash, forKey: "progressionHash")
    }

    public static func == (lhs: DestinyDefinitionsDirectorDestinyActivityGraphDisplayProgressionDefinition, rhs: DestinyDefinitionsDirectorDestinyActivityGraphDisplayProgressionDefinition) -> Bool {
        guard lhs.id == rhs.id else { return false }
        guard lhs.progressionHash == rhs.progressionHash else { return false }
        return true
    }
}
