//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsCommonDestinyPositionDefinition: APIModel {

    public var x: Int?

    public var y: Int?

    public var z: Int?

    public init(x: Int? = nil, y: Int? = nil, z: Int? = nil) {
        self.x = x
        self.y = y
        self.z = z
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        x = try container.decodeIfPresent("x")
        y = try container.decodeIfPresent("y")
        z = try container.decodeIfPresent("z")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(x, forKey: "x")
        try container.encodeIfPresent(y, forKey: "y")
        try container.encodeIfPresent(z, forKey: "z")
    }

    public static func == (lhs: DestinyDefinitionsCommonDestinyPositionDefinition, rhs: DestinyDefinitionsCommonDestinyPositionDefinition) -> Bool {
        guard lhs.x == rhs.x else { return false }
        guard lhs.y == rhs.y else { return false }
        guard lhs.z == rhs.z else { return false }
        return true
    }
}
