//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Talent nodes have requirements that must be met before they can be activated.
This describes the material costs, the Level of the Talent Grid's progression required, and other conditional information that limits whether a talent node can be activated. */
public struct DestinyDefinitionsDestinyNodeActivationRequirement: APIModel {

    /** The Progression level on the Talent Grid required to activate this node.
See DestinyTalentGridDefinition.progressionHash for the related Progression, and read DestinyProgressionDefinition's documentation to learn more about Progressions. */
    public var gridLevel: Int?

    /** The list of hash identifiers for material requirement sets: materials that are required for the node to be activated. See DestinyMaterialRequirementSetDefinition for more information about material requirements.
In this case, only a single DestinyMaterialRequirementSetDefinition will be chosen from this list, and we won't know which one will be chosen until an instance of the item is created. */
    public var materialRequirementHashes: [Int]?

    public init(gridLevel: Int? = nil, materialRequirementHashes: [Int]? = nil) {
        self.gridLevel = gridLevel
        self.materialRequirementHashes = materialRequirementHashes
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        gridLevel = try container.decodeIfPresent("gridLevel")
        materialRequirementHashes = try container.decodeArrayIfPresent("materialRequirementHashes")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(gridLevel, forKey: "gridLevel")
        try container.encodeIfPresent(materialRequirementHashes, forKey: "materialRequirementHashes")
    }

    public static func == (lhs: DestinyDefinitionsDestinyNodeActivationRequirement, rhs: DestinyDefinitionsDestinyNodeActivationRequirement) -> Bool {
        guard lhs.gridLevel == rhs.gridLevel else { return false }
        guard lhs.materialRequirementHashes == rhs.materialRequirementHashes else { return false }
        return true
    }
}
