//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** This is a bit of an odd duck. Apparently, if talent nodes steps have this data, the game will go through on step activation and alter the first Socket it finds on the item that has a type matching the given socket type, inserting the indicated plug item. */
public struct DestinyDefinitionsDestinyNodeSocketReplaceResponse: APIModel {

    /** The hash identifier of the plug item that will be inserted into the socket found. */
    public var plugItemHash: Int?

    /** The hash identifier of the socket type to find amidst the item's sockets (the item to which this talent grid is attached). See DestinyInventoryItemDefinition.sockets.socketEntries to find the socket type of sockets on the item in question. */
    public var socketTypeHash: Int?

    public init(plugItemHash: Int? = nil, socketTypeHash: Int? = nil) {
        self.plugItemHash = plugItemHash
        self.socketTypeHash = socketTypeHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        plugItemHash = try container.decodeIfPresent("plugItemHash")
        socketTypeHash = try container.decodeIfPresent("socketTypeHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(plugItemHash, forKey: "plugItemHash")
        try container.encodeIfPresent(socketTypeHash, forKey: "socketTypeHash")
    }

    public static func == (lhs: DestinyDefinitionsDestinyNodeSocketReplaceResponse, rhs: DestinyDefinitionsDestinyNodeSocketReplaceResponse) -> Bool {
        guard lhs.plugItemHash == rhs.plugItemHash else { return false }
        guard lhs.socketTypeHash == rhs.socketTypeHash else { return false }
        return true
    }
}
