//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** When a vendor provides services, this is the localized name of those services. */
public struct DestinyDefinitionsDestinyVendorServiceDefinition: APIModel {

    /** The localized name of a service provided. */
    public var name: String?

    public init(name: String? = nil) {
        self.name = name
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        name = try container.decodeIfPresent("name")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(name, forKey: "name")
    }

    public static func == (lhs: DestinyDefinitionsDestinyVendorServiceDefinition, rhs: DestinyDefinitionsDestinyVendorServiceDefinition) -> Bool {
        guard lhs.name == rhs.name else { return false }
        return true
    }
}
