//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsMilestonesDestinyMilestoneChallengeDefinition: APIModel {

    /** The challenge related to this milestone. */
    public var challengeObjectiveHash: Int?

    public init(challengeObjectiveHash: Int? = nil) {
        self.challengeObjectiveHash = challengeObjectiveHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        challengeObjectiveHash = try container.decodeIfPresent("challengeObjectiveHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(challengeObjectiveHash, forKey: "challengeObjectiveHash")
    }

    public static func == (lhs: DestinyDefinitionsMilestonesDestinyMilestoneChallengeDefinition, rhs: DestinyDefinitionsMilestonesDestinyMilestoneChallengeDefinition) -> Bool {
        guard lhs.challengeObjectiveHash == rhs.challengeObjectiveHash else { return false }
        return true
    }
}
