//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A list of minimal information for items in an inventory: be it a character's inventory, or a Profile's inventory. (Note that the Vault is a collection of inventory buckets in the Profile's inventory)
Inventory Items returned here are in a flat list, but importantly they have a bucketHash property that indicates the specific inventory bucket that is holding them. These buckets constitute things like the separate sections of the Vault, the user's inventory slots, etc. See DestinyInventoryBucketDefinition for more info. */
public struct DestinyEntitiesInventoryDestinyInventoryComponent: APIModel {

    /** The items in this inventory. If you care to bucket them, use the item's bucketHash property to group them. */
    public var items: [DestinyEntitiesItemsDestinyItemComponent]?

    public init(items: [DestinyEntitiesItemsDestinyItemComponent]? = nil) {
        self.items = items
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        items = try container.decodeArrayIfPresent("items")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(items, forKey: "items")
    }

    public static func == (lhs: DestinyEntitiesInventoryDestinyInventoryComponent, rhs: DestinyEntitiesInventoryDestinyInventoryComponent) -> Bool {
        guard lhs.items == rhs.items else { return false }
        return true
    }
}
