//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyArtifactsDestinyArtifactTierItem: APIModel {

    public var isActive: Bool?

    public var itemHash: Int?

    public init(isActive: Bool? = nil, itemHash: Int? = nil) {
        self.isActive = isActive
        self.itemHash = itemHash
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        isActive = try container.decodeIfPresent("isActive")
        itemHash = try container.decodeIfPresent("itemHash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(isActive, forKey: "isActive")
        try container.encodeIfPresent(itemHash, forKey: "itemHash")
    }

    public static func == (lhs: DestinyArtifactsDestinyArtifactTierItem, rhs: DestinyArtifactsDestinyArtifactTierItem) -> Bool {
        guard lhs.isActive == rhs.isActive else { return false }
        guard lhs.itemHash == rhs.itemHash else { return false }
        return true
    }
}
