//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A Flags enumeration/bitmask where each bit represents a possible state that a Record/Triumph can be in. */
/** A Flags enumeration/bitmask where each bit represents a possible state that a Record/Triumph can be in. */
public enum DestinyDestinyRecordState: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case _4 = 4
    case _8 = 8
    case _16 = 16
    case _32 = 32
    case _64 = 64
}
