//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** If a Milestone has one or more Quests, this will contain the live information for the character's status with one of those quests. */
public struct DestinyMilestonesDestinyMilestoneQuest: APIModel {

    /** *IF* the Milestone has an active Activity that can give you greater details about what you need to do, it will be returned here. Remember to associate this with the DestinyMilestoneDefinition's activities to get details about the activity, including what specific quest it is related to if you have multiple quests to choose from. */
    public var activity: [String: Any]?

    /** The activities referred to by this quest can have many associated challenges. They are all contained here, with activityHashes so that you can associate them with the specific activity variants in which they can be found. In retrospect, I probably should have put these under the specific Activity Variants, but it's too late to change it now. Theoretically, a quest without Activities can still have Challenges, which is why this is on a higher level than activity/variants, but it probably should have been in both places. That may come as a later revision. */
    public var challenges: [DestinyChallengesDestinyChallengeStatus]?

    /** Quests are defined as Items in content. As such, this is the hash identifier of the DestinyInventoryItemDefinition that represents this quest. It will have pointers to all of the steps in the quest, and display information for the quest (title, description, icon etc) Individual steps will be referred to in the Quest item's DestinyInventoryItemDefinition.setData property, and themselves are Items with their own renderable data. */
    public var questItemHash: Int?

    /** The current status of the quest for the character making the request. */
    public var status: [String: Any]?

    public init(activity: [String: Any]? = nil, challenges: [DestinyChallengesDestinyChallengeStatus]? = nil, questItemHash: Int? = nil, status: [String: Any]? = nil) {
        self.activity = activity
        self.challenges = challenges
        self.questItemHash = questItemHash
        self.status = status
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        activity = try container.decodeAnyIfPresent("activity")
        challenges = try container.decodeArrayIfPresent("challenges")
        questItemHash = try container.decodeIfPresent("questItemHash")
        status = try container.decodeAnyIfPresent("status")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeAnyIfPresent(activity, forKey: "activity")
        try container.encodeIfPresent(challenges, forKey: "challenges")
        try container.encodeIfPresent(questItemHash, forKey: "questItemHash")
        try container.encodeAnyIfPresent(status, forKey: "status")
    }

    public static func == (lhs: DestinyMilestonesDestinyMilestoneQuest, rhs: DestinyMilestonesDestinyMilestoneQuest) -> Bool {
        guard NSDictionary(dictionary: lhs.activity ?? [:]).isEqual(to: rhs.activity ?? [:]) else { return false }
        guard lhs.challenges == rhs.challenges else { return false }
        guard lhs.questItemHash == rhs.questItemHash else { return false }
        guard NSDictionary(dictionary: lhs.status ?? [:]).isEqual(to: rhs.status ?? [:]) else { return false }
        return true
    }
}
