//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Represents the possible components that can be returned from Destiny "Get" calls such as GetProfile, GetCharacter, GetVendor etc...
When making one of these requests, you will pass one or more of these components as a comma separated list in the "?components=" querystring parameter. For instance, if you want baseline Profile data, Character Data, and character progressions, you would pass "?components=Profiles,Characters,CharacterProgressions" You may use either the numerical or string values. */
/** Represents the possible components that can be returned from Destiny "Get" calls such as GetProfile, GetCharacter, GetVendor etc...
When making one of these requests, you will pass one or more of these components as a comma separated list in the "?components=" querystring parameter. For instance, if you want baseline Profile data, Character Data, and character progressions, you would pass "?components=Profiles,Characters,CharacterProgressions" You may use either the numerical or string values. */
public enum DestinyDestinyComponentType: Int, Codable, Equatable, CaseIterable {
    case _0 = 0
    case _100 = 100
    case _101 = 101
    case _102 = 102
    case _103 = 103
    case _104 = 104
    case _105 = 105
    case _200 = 200
    case _201 = 201
    case _202 = 202
    case _203 = 203
    case _204 = 204
    case _205 = 205
    case _300 = 300
    case _301 = 301
    case _302 = 302
    case _303 = 303
    case _304 = 304
    case _305 = 305
    case _306 = 306
    case _307 = 307
    case _308 = 308
    case _309 = 309
    case _310 = 310
    case _400 = 400
    case _401 = 401
    case _402 = 402
    case _500 = 500
    case _600 = 600
    case _700 = 700
    case _800 = 800
    case _900 = 900
    case _1000 = 1000
}
