//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Represents a status string that could be conditionally displayed about an activity. Note that externally, you can only see the strings themselves. Internally we combine this information with server state to determine which strings should be shown. */
public struct DestinyDefinitionsDestinyActivityUnlockStringDefinition: APIModel {

    /** The string to be displayed if the conditions are met. */
    public var displayString: String?

    public init(displayString: String? = nil) {
        self.displayString = displayString
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        displayString = try container.decodeIfPresent("displayString")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(displayString, forKey: "displayString")
    }

    public static func == (lhs: DestinyDefinitionsDestinyActivityUnlockStringDefinition, rhs: DestinyDefinitionsDestinyActivityUnlockStringDefinition) -> Bool {
        guard lhs.displayString == rhs.displayString else { return false }
        return true
    }
}
