//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct DestinyDefinitionsAnimationsDestinyAnimationReference: APIModel {

    public var animIdentifier: String?

    public var animName: String?

    public var path: String?

    public init(animIdentifier: String? = nil, animName: String? = nil, path: String? = nil) {
        self.animIdentifier = animIdentifier
        self.animName = animName
        self.path = path
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        animIdentifier = try container.decodeIfPresent("animIdentifier")
        animName = try container.decodeIfPresent("animName")
        path = try container.decodeIfPresent("path")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(animIdentifier, forKey: "animIdentifier")
        try container.encodeIfPresent(animName, forKey: "animName")
        try container.encodeIfPresent(path, forKey: "path")
    }

    public static func == (lhs: DestinyDefinitionsAnimationsDestinyAnimationReference, rhs: DestinyDefinitionsAnimationsDestinyAnimationReference) -> Bool {
        guard lhs.animIdentifier == rhs.animIdentifier else { return false }
        guard lhs.animName == rhs.animName else { return false }
        guard lhs.path == rhs.path else { return false }
        return true
    }
}
