//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** A response containing all of the components for all requested vendors. */
public struct DestinyResponsesInventoryChangedResponse: APIModel {

    /** Items that appeared in the inventory possibly as a result of an action. */
    public var addedInventoryItems: [DestinyEntitiesItemsDestinyItemComponent]?

    /** Items that disappeared from the inventory possibly as a result of an action. */
    public var removedInventoryItems: [DestinyEntitiesItemsDestinyItemComponent]?

    public init(addedInventoryItems: [DestinyEntitiesItemsDestinyItemComponent]? = nil, removedInventoryItems: [DestinyEntitiesItemsDestinyItemComponent]? = nil) {
        self.addedInventoryItems = addedInventoryItems
        self.removedInventoryItems = removedInventoryItems
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        addedInventoryItems = try container.decodeArrayIfPresent("addedInventoryItems")
        removedInventoryItems = try container.decodeArrayIfPresent("removedInventoryItems")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(addedInventoryItems, forKey: "addedInventoryItems")
        try container.encodeIfPresent(removedInventoryItems, forKey: "removedInventoryItems")
    }

    public static func == (lhs: DestinyResponsesInventoryChangedResponse, rhs: DestinyResponsesInventoryChangedResponse) -> Bool {
        guard lhs.addedInventoryItems == rhs.addedInventoryItems else { return false }
        guard lhs.removedInventoryItems == rhs.removedInventoryItems else { return false }
        return true
    }
}
