//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct FireteamFireteamResponse: APIModel {

    public var alternates: [FireteamFireteamMember]?

    public var members: [FireteamFireteamMember]?

    public var summary: FireteamFireteamSummary?

    public init(alternates: [FireteamFireteamMember]? = nil, members: [FireteamFireteamMember]? = nil, summary: FireteamFireteamSummary? = nil) {
        self.alternates = alternates
        self.members = members
        self.summary = summary
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        alternates = try container.decodeArrayIfPresent("Alternates")
        members = try container.decodeArrayIfPresent("Members")
        summary = try container.decodeIfPresent("Summary")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(alternates, forKey: "Alternates")
        try container.encodeIfPresent(members, forKey: "Members")
        try container.encodeIfPresent(summary, forKey: "Summary")
    }

    public static func == (lhs: FireteamFireteamResponse, rhs: FireteamFireteamResponse) -> Bool {
        guard lhs.alternates == rhs.alternates else { return false }
        guard lhs.members == rhs.members else { return false }
        guard lhs.summary == rhs.summary else { return false }
        return true
    }
}
