//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct GroupsV2GroupBanRequest: APIModel {

    public var comment: String?

    public var length: Int?

    public init(comment: String? = nil, length: Int? = nil) {
        self.comment = comment
        self.length = length
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        comment = try container.decodeIfPresent("comment")
        length = try container.decodeIfPresent("length")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(comment, forKey: "comment")
        try container.encodeIfPresent(length, forKey: "length")
    }

    public static func == (lhs: GroupsV2GroupBanRequest, rhs: GroupsV2GroupBanRequest) -> Bool {
        guard lhs.comment == rhs.comment else { return false }
        guard lhs.length == rhs.length else { return false }
        return true
    }
}
