//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct GroupsV2GroupMembership: APIModel {

    public var group: GroupsV2GroupV2?

    public var member: GroupsV2GroupMember?

    public init(group: GroupsV2GroupV2? = nil, member: GroupsV2GroupMember? = nil) {
        self.group = group
        self.member = member
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        group = try container.decodeIfPresent("group")
        member = try container.decodeIfPresent("member")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(group, forKey: "group")
        try container.encodeIfPresent(member, forKey: "member")
    }

    public static func == (lhs: GroupsV2GroupMembership, rhs: GroupsV2GroupMembership) -> Bool {
        guard lhs.group == rhs.group else { return false }
        guard lhs.member == rhs.member else { return false }
        return true
    }
}
