//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct TrendingTrendingCategories: APIModel {

    public var categories: [TrendingTrendingCategory]?

    public init(categories: [TrendingTrendingCategory]? = nil) {
        self.categories = categories
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        categories = try container.decodeArrayIfPresent("categories")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(categories, forKey: "categories")
    }

    public static func == (lhs: TrendingTrendingCategories, rhs: TrendingTrendingCategories) -> Bool {
        guard lhs.categories == rhs.categories else { return false }
        return true
    }
}
