//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality. */
public struct BungieNetAPI {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = true

    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ")

    public static let version = "2.4.1"

    public enum App {}
    public enum CommunityContent {}
    public enum Content {}
    public enum Core {}
    public enum Destiny2 {}
    public enum Fireteam {}
    public enum Forum {}
    public enum GroupV2 {}
    public enum Preview {}
    public enum Trending {}
    public enum User {}

    public enum Server {

        /** The endpoint for accessing the Bungie.net API.  You probably guessed that already. **/
        public static let main = "https://www.bungie.net/Platform"
    }
}
