//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension BungieNetAPI.Destiny2 {

    /** Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation. */
    public enum Destiny2GetLeaderboardsForCharacter {

        public static let service = APIService<Response>(id: "Destiny2.GetLeaderboardsForCharacter", tag: "Destiny2", method: "GET", path: "/Destiny2/Stats/Leaderboards/{membershipType}/{destinyMembershipId}/{characterId}/", hasBody: false)

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** The specific character to build the leaderboard around for the provided Destiny Membership. */
                public var characterId: Int

                /** The Destiny membershipId of the user to retrieve. */
                public var destinyMembershipId: Int

                /** Maximum number of top players to return. Use a large number to get entire leaderboard. */
                public var maxtop: Int?

                /** A valid non-BungieNet membership type. */
                public var membershipType: Int

                /** List of game modes for which to get leaderboards. See the documentation for DestinyActivityModeType for valid values, and pass in string representation, comma delimited. */
                public var modes: String?

                /** ID of stat to return rather than returning all Leaderboard stats. */
                public var statid: String?

                public init(characterId: Int, destinyMembershipId: Int, maxtop: Int? = nil, membershipType: Int, modes: String? = nil, statid: String? = nil) {
                    self.characterId = characterId
                    self.destinyMembershipId = destinyMembershipId
                    self.maxtop = maxtop
                    self.membershipType = membershipType
                    self.modes = modes
                    self.statid = statid
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: Destiny2GetLeaderboardsForCharacter.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(characterId: Int, destinyMembershipId: Int, maxtop: Int? = nil, membershipType: Int, modes: String? = nil, statid: String? = nil) {
                let options = Options(characterId: characterId, destinyMembershipId: destinyMembershipId, maxtop: maxtop, membershipType: membershipType, modes: modes, statid: statid)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "characterId" + "}", with: "\(self.options.characterId)").replacingOccurrences(of: "{" + "destinyMembershipId" + "}", with: "\(self.options.destinyMembershipId)").replacingOccurrences(of: "{" + "membershipType" + "}", with: "\(self.options.membershipType)")
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let maxtop = options.maxtop {
                  params["maxtop"] = maxtop
                }
                if let modes = options.modes {
                  params["modes"] = modes
                }
                if let statid = options.statid {
                  params["statid"] = statid
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {

            /** Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation. */
            public struct Status200: APIModel {

                public var detailedErrorTrace: String?

                public var errorCode: Int?

                public var errorStatus: String?

                public var message: String?

                public var messageData: [String: String]?

                public var response: [String: [String: DestinyHistoricalStatsDestinyLeaderboard]]?

                public var throttleSeconds: Int?

                public init(detailedErrorTrace: String? = nil, errorCode: Int? = nil, errorStatus: String? = nil, message: String? = nil, messageData: [String: String]? = nil, response: [String: [String: DestinyHistoricalStatsDestinyLeaderboard]]? = nil, throttleSeconds: Int? = nil) {
                    self.detailedErrorTrace = detailedErrorTrace
                    self.errorCode = errorCode
                    self.errorStatus = errorStatus
                    self.message = message
                    self.messageData = messageData
                    self.response = response
                    self.throttleSeconds = throttleSeconds
                }

                public init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: StringCodingKey.self)

                    detailedErrorTrace = try container.decodeIfPresent("DetailedErrorTrace")
                    errorCode = try container.decodeIfPresent("ErrorCode")
                    errorStatus = try container.decodeIfPresent("ErrorStatus")
                    message = try container.decodeIfPresent("Message")
                    messageData = try container.decodeIfPresent("MessageData")
                    response = try container.decodeIfPresent("Response")
                    throttleSeconds = try container.decodeIfPresent("ThrottleSeconds")
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: StringCodingKey.self)

                    try container.encodeIfPresent(detailedErrorTrace, forKey: "DetailedErrorTrace")
                    try container.encodeIfPresent(errorCode, forKey: "ErrorCode")
                    try container.encodeIfPresent(errorStatus, forKey: "ErrorStatus")
                    try container.encodeIfPresent(message, forKey: "Message")
                    try container.encodeIfPresent(messageData, forKey: "MessageData")
                    try container.encodeIfPresent(response, forKey: "Response")
                    try container.encodeIfPresent(throttleSeconds, forKey: "ThrottleSeconds")
                }

                public static func == (lhs: Status200, rhs: Status200) -> Bool {
                    guard lhs.detailedErrorTrace == rhs.detailedErrorTrace else { return false }
                    guard lhs.errorCode == rhs.errorCode else { return false }
                    guard lhs.errorStatus == rhs.errorStatus else { return false }
                    guard lhs.message == rhs.message else { return false }
                    guard lhs.messageData == rhs.messageData else { return false }
                    guard lhs.response == rhs.response else { return false }
                    guard lhs.throttleSeconds == rhs.throttleSeconds else { return false }
                    return true
                }
            }
            public typealias SuccessType = Status200

            /** Look at the Response property for more information about the nature of this response */
            case status200(Status200)

            public var success: Status200? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Status200.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
